env:
  node: true
  es2021: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  quotes:
    - error
    - single
